name: shopstag
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dots_indicator: ^2.0.0
  get: ^4.1.4
  oktoast: ^3.3.0
  badges: ^2.0.3
  auto_size_text: ^3.0.0
  stroke_text: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/
  fonts:
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto-Black.ttf
           weight: 400
         - asset: assets/fonts/Roboto-Black.ttf
           weight: 400
         - asset: assets/fonts/Roboto-Black.ttf
           weight: 400
         - asset: assets/fonts/Roboto-Black.ttf
           weight: 400
